### ISSUE TITLE
m.login.application_service type possibly missing?

### ISSUE THREAD

**Issue by nbartels** [kelaresg/go-skype-bridge#8]
I configured the bridge and hopefully did everything correct, but the bridge writes this error in the log. The error is returned from the synapse server.

```
Failed to connect to homeserver: failed to ensure registered: failed to POST /_matrix/client/r0/register: M_UNKNOWN (HTTP 400): An access token should not be provided on requests to /register (except if type is m.login.application_service). Retrying in 10 seconds...
```

**Comment by Rutherther** [comment]
This type needs to be specified since Synapse 1.32.0rc1, before then it was allowed to send registration without it. This change was announced by Synapse in releases on Mar 22, latest commit to `go-skype-bridge` master was on Feb 6, so it makes sense it doesn't work now.

The particular problem lays in `mautrix-go` library version that is used (`github.com/pidongqianqian/mautrix-go v0.8.0-rc.4.0.20201208081810-787323a21113`) where line with type is still missing as it's older commit. (This is the particular line where the type should be https://github.com/pidongqianqian/mautrix-go/blob/787323a21113415793e3d12882bf482bb259f907/appservice/intent.go#L50)

This problem should already be fixed in develop branch of `go-skype-bridge` where newer version of the `mautrix-go` library is used with this line added. **As a workaround** develop version could be used.

I am not sure whether I can help more here as I don't know what else is needed to make to merge develop to master so that it would resolve this issue. Another solution would be just updating the library version on master. Both solutions could cause some new issues. I myself tried to just update the library version and it seems to work fine though I haven't tested every feature of the bot yet.

**Comment by pidongqianqian** [comment]
It should be fine now, the develop branch has been merged into the master branch.

**Comment by Rutherther** [comment]
I've tested it and I've got this error when running `go build`:
```
go: github.com/kelaresg/go-skypeapi@v0.1.2-0.20210603114428-9c103d451110: missing go.sum entry; to add it:
	go mod download github.com/kelaresg/go-skypeapi
```

After running `go mod tidy` and thus updating `go.sum` it works fine (and I am sure the updated version was built). Is this problem just at my end or does the `go.sum` really need to be updated?

**Comment by pidongqianqian** [comment]
@Rutherther you are right :),  go.sum need update, and now is ok.
